apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-service-account
  namespace: rabbitmq-golang
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rabbitmq-role
  namespace: rabbitmq-golang
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rabbitmq-role-binding
  namespace: rabbitmq-golang
subjects:
  - kind: ServiceAccount
    name: rabbitmq-service-account
    namespace: rabbitmq-golang
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-role
